config/routes.rb
Rails.application.routes.draw do
  # topページへのルート
  root to: 'top#index'

  # コールバックページへの遷移
  get '/oauth/twitter/callback', to: 'callbacks#callback'
  get '/oauth/google/callback', to: 'callbacks#callback'
  # api認証、DBからデータを取得する用のルート
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:password], controllers: {
        registrations: 'api/v1/auth/registrations',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks'
      }
      resources :modes, only: %i[index] do
        resources :selects, only: %i[index show]
      end
      resources :play_results, only: %i[index create destroy]
    end
  end

  # 管理者用ルート
  devise_for :admins, skip: %i[registrations password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :modes
    resources :sentences
  end

  # 違うpathのURLの時topページへ遷移するルート
  get '*path', to: 'top#index'
end

app/models/mode.rb
# == Schema Information
#
# Table name: modes
#
#  id          :integer          not null, primary key
#  description :string(30)       not null
#  difficulty  :string(10)       not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_modes_on_difficulty  (difficulty) UNIQUE
#
class Mode < ApplicationRecord
  has_many :sentences, dependent: :destroy

  validates :difficulty, uniqueness: true, presence: true, length: { maximum: 10 }
  validates :description, presence: true,  length: { maximum: 30 }
end

app/controllers/admins/modes_controller.rb
class Admins::ModesController < Admins::ApplicationController
  before_action :set_mode, only: %i[edit update show destroy]

  def index
    @modes = Mode.page(params[:page]).per(8).order(:id)
  end

  def new
    @mode = Mode.new
  end

  def edit; end

  def create
    @mode = Mode.new(mode_params)
    if @mode.save
      redirect_to admins_modes_path,
                  success: t('defaults.message.created', item: Mode.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Mode.model_name.human)
      render :new
    end
  end

  def update
    if @mode.update(mode_params)
      redirect_to admins_mode_path(@mode),
                  success: t('defaults.message.updated', item: Mode.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Mode.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @mode.destroy!
    redirect_to admins_modes_path,
                success: t('defaults.message.deleted', item: Mode.model_name.human)
  end

  private

  def set_mode
    @mode = Mode.find(params[:id])
  end

  def mode_params
    params.require(:mode).permit(:difficulty, :description)
  end
end

app/controllers/api/v1/modes_controller.rb
class Api::V1::ModesController < Api::V1::ApplicationController
  def index
    @modes = Mode.all.order(:id)
    render 'jb/mode/index.json.jb'
  end
end

app/views/admins/modes/_mode.html.erb
<tr>
  <td>
    <%= mode.id %>
  </td>
  <td>
    <%= mode.difficulty %>
  </td>
  <td>
    <%= mode.description %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admins_mode_path(mode), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admins_mode_path(mode), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admins_mode_path(mode), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admins/modes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <%= form_with model: @mode, url: admins_mode_path(@mode) do |f| %>
        <%= render 'admins/shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :difficulty %>
          <%= f.text_field :difficulty, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/modes/index.html.erb
<div class="container mb-5 pt-2">
  <h1 class="pt-5"><%= t('.title') %></h1>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Mode.human_attribute_name(:id) %></th>
          <th scope="col"><%= Mode.human_attribute_name(:difficulty) %></th>
          <th scope="col"><%= Mode.human_attribute_name(:description) %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @modes %>
        </tbody>
      </table>
    </div>
    <%= paginate @modes %>
  </div>
</div>

app/views/admins/modes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <%= form_with model: @mode,  url: admins_modes_path do |f| %>
        <%= render 'admins/shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :difficulty %>
          <%= f.text_field :difficulty, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/modes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admins_mode_path(@mode), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admins_mode_path(@mode), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Mode.human_attribute_name(:id) %></th>
          <td><%= @mode.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Mode.human_attribute_name(:title) %></th>
          <td><%= @mode.difficulty %></td>
        </tr>
        <tr>
          <th scope="row"><%= Mode.human_attribute_name(:user) %></th>
          <td><%= @mode.description %></td>
        </tr>
        <tr>
          <th scope="row"><%= Mode.human_attribute_name(:created_at) %></th>
          <td><%= l @mode.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>