config/routes.rb
Rails.application.routes.draw do
  # topページへのルート
  root to: 'top#index'

  # コールバックページへの遷移
  get '/oauth/twitter/callback', to: 'callbacks#callback'
  get '/oauth/google/callback', to: 'callbacks#callback'
  # api認証、DBからデータを取得する用のルート
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:password], controllers: {
        registrations: 'api/v1/auth/registrations',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks'
      }
      resources :modes, only: %i[index] do
        resources :selects, only: %i[index show]
      end
      resources :play_results, only: %i[index create destroy]
    end
  end

  # 管理者用ルート
  devise_for :admins, skip: %i[registrations password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :modes
    resources :sentences
  end

  # 違うpathのURLの時topページへ遷移するルート
  get '*path', to: 'top#index'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  email              :string           not null
#  encrypted_password :string           default(""), not null
#  image              :string
#  name               :string(50)       not null
#  nickname           :string(50)
#  provider           :string           default("email"), not null
#  tokens             :json
#  uid                :string           default(""), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_users_on_uid_and_provider  (uid,provider) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :play_results, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  validates :name, presence: true, length: { maximum: 50 }
  validates :nickname, length: { maximum: 50 }
  validates :email, presence: true
  include DeviseTokenAuth::Concerns::User
end

app/controllers/admin/user_controller.rb
before_action :set_user, only: %i[edit update show destroy]

  def index
    @users = User.all.order(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path,
                  success: t('defaults.message.created', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: User.model_name.human)
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user),
                  success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @user.destroy!
    redirect_to admin_users_path,
                success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def sentence_params
    params.require(:user).permit(:name, :email, :role)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  before_action :set_user, only: %i[edit update show destroy]

  def index
    @users = User.all.page(params[:page]).per(8).order(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_users_path,
                  success: t('defaults.message.created', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: User.model_name.human)
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(update_user_params)
      redirect_to admins_user_path(@user),
                  success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @user.destroy!
    redirect_to admins_users_path,
                success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:name, :email)
  end
end

app/views/admins/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.email %>
  <td>
    <%= link_to t('defaults.show'), admins_user_path(user), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admins_user_path(user), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admins_user_path(user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admins/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <%= form_with model: @user, url: admins_user_path(@user) do |f| %>
        <%= render 'admins/shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
          <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class="container mb-5 pt-2">
  <h1 class="pt-5"><%= t('.title') %></h1>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:name) %></th>
          <th scope="col"><%= User.human_attribute_name(:email) %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @users %>
        </tbody>
      </table>
    </div>
    <%= paginate @users %>
  </div>
</div>

app/views/admins/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <%= form_with model: @user, url: admins_users_path do |f| %>
        <%= render 'admins/shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.text_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.text_field :password_confirmation, class: 'form-control' %>
        </div>
          <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admins_user_path(@user), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admins_user_path(@user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:id) %></th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:name) %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:email) %></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:created_at) %></th>
          <td><%= l @user.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>