config/routes.rb
Rails.application.routes.draw do
  # topページへのルート
  root to: 'top#index'

  # コールバックページへの遷移
  get '/oauth/twitter/callback', to: 'callbacks#callback'
  get '/oauth/google/callback', to: 'callbacks#callback'
  # api認証、DBからデータを取得する用のルート
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:password], controllers: {
        registrations: 'api/v1/auth/registrations',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks'
      }
      resources :modes, only: %i[index] do
        resources :selects, only: %i[index show]
      end
      resources :play_results, only: %i[index create destroy]
    end
  end

  # 管理者用ルート
  devise_for :admins, skip: %i[registrations password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :modes
    resources :sentences
  end

  # 違うpathのURLの時topページへ遷移するルート
  get '*path', to: 'top#index'
end

app/models/sentence.rb
# == Schema Information
#
# Table name: sentences
#
#  id         :integer          not null, primary key
#  boin       :string(20)       not null
#  normal     :string(20)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  mode_id    :integer
#
# Indexes
#
#  index_sentences_on_boin     (boin) UNIQUE
#  index_sentences_on_mode_id  (mode_id)
#  index_sentences_on_normal   (normal) UNIQUE
#
# Foreign Keys
#
#  mode_id  (mode_id => modes.id)
#
class Sentence < ApplicationRecord
  belongs_to :mode

  validates :normal, uniqueness: true, presence: true, length: { maximum: 20 }
  validates :boin, uniqueness: true, presence: true, length: { maximum: 20 }
end

app/controllers/admins/sentences_controller.rb
class Admins::SentencesController < Admins::ApplicationController
  before_action :set_sentence, only: %i[edit update show destroy]

  def index
    @sentences = Sentence.all.page(params[:page]).per(8).order(:id)
  end

  def new
    @sentence = Sentence.new
  end

  def create
    @sentence = Sentence.new(sentence_params)
    if @sentence.save
      redirect_to admins_sentences_path,
                  success: t('defaults.message.created', item: Sentence.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Sentence.model_name.human)
      render :new
    end
  end

  def edit; end

  def update
    if @sentence.update(sentence_params)
      redirect_to admins_sentence_path(@sentence),
                  success: t('defaults.message.updated', item: Sentence.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Sentence.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @sentence.destroy!
    redirect_to admins_sentences_path,
                success: t('defaults.message.deleted', item: Sentence.model_name.human)
  end

  private

  def set_sentence
    @sentence = Sentence.find(params[:id])
  end

  def sentence_params
    params.require(:sentence).permit(:boin, :normal, :mode_id)
  end
end

app/views/admins/sentences/_sentence.html.erb
<tr>
  <td>
    <%= sentence.id %>
  </td>
  <td>
    <%= sentence.normal %>
  <td>
    <%= sentence.boin %>
  </td>
  <td>
    <%= sentence.mode.difficulty %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admins_sentence_path(sentence), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admins_sentence_path(sentence), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admins_sentence_path(sentence), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admins/sentences/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <%= form_with model: @sentence, url: admins_sentence_path(@sentence) do |f| %>
        <%= render 'admins/shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :normal %>
          <%= f.text_field :normal, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :boin %>
          <%= f.text_area :boin, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :mode_id %>
          <%= f.collection_select :mode_id, Mode.all, :id, :difficulty %>
        </div>
          <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/sentences/index.html.erb
<div class="container mb-5 pt-2">
  <h1 class="pt-5"><%= t('.title') %></h1>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Sentence.human_attribute_name(:id) %></th>
          <th scope="col"><%= Sentence.human_attribute_name(:normal) %></th>
          <th scope="col"><%= Sentence.human_attribute_name(:boin) %></th>
          <th scope="col"><%= Sentence.human_attribute_name(:mode_id) %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @sentences %>
        </tbody>
      </table>
    </div>
    <%= paginate @sentences %>
  </div>
</div>

app/views/admins/sentences/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <%= form_with model: @sentence, url: admins_sentences_path do |f| %>
        <%= render 'admins/shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :normal %>
          <%= f.text_field :normal, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :boin %>
          <%= f.text_area :boin, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :mode_id %>
          <%= f.collection_select :mode_id, Mode.all, :id, :difficulty %>
        </div>
          <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/sentences/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1 class="pt-5"><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admins_sentence_path(@sentence), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admins_sentence_path(@sentence), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Sentence.human_attribute_name(:id) %></th>
          <td><%= @sentence.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Sentence.human_attribute_name(:title) %></th>
          <td><%= @sentence.normal %></td>
        </tr>
        <tr>
          <th scope="row"><%= Sentence.human_attribute_name(:user) %></th>
          <td><%= @sentence.boin %></td>
        </tr>
        <tr>
          <th scope="row"><%= Sentence.human_attribute_name(:mode_id) %></th>
          <td><%= @sentence.mode.difficulty %></td>
        </tr>
        <tr>
          <th scope="row"><%= Sentence.human_attribute_name(:created_at) %></th>
          <td><%= l @sentence.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>