config/routes.rb
Rails.application.routes.draw do
  # topページへのルート
  root to: 'top#index'

  # コールバックページへの遷移
  get '/oauth/twitter/callback', to: 'callbacks#callback'
  get '/oauth/google/callback', to: 'callbacks#callback'
  # api認証、DBからデータを取得する用のルート
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:password], controllers: {
        registrations: 'api/v1/auth/registrations',
        omniauth_callbacks: 'api/v1/auth/omniauth_callbacks'
      }
      resources :modes, only: %i[index] do
        resources :selects, only: %i[index show]
      end
      resources :play_results, only: %i[index create destroy]
    end
  end

  # 管理者用ルート
  devise_for :admins, skip: %i[registrations password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root to: 'dashboards#index'
    resources :users
    resources :modes
    resources :sentences
  end

  # 違うpathのURLの時topページへ遷移するルート
  get '*path', to: 'top#index'
end

app/views/admins/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/admins/shared/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; 2022 BOIトレ.</strong>
  All rights reserved.
</footer>

app/views/admins/shared/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
  </ul>
</nav>

app/views/admins/shared/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to admins_root_path, class: "brand-link" do %>
    <%= image_tag 'AdminLTELogo.png', class: 'brand-image img-circle elevation-3' %>
    <span class="brand-text font-weight-light">BOIトレ管理画面</span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to admins_users_path, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              Users
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admins_modes_path, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              Modes
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admins_sentences_path, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              Sentences
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_admins_user_path, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              ユーザー新規作成
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_admins_mode_path, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              モード新規作成
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_admins_sentence_path, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              文章新規作成
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              ログアウト
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>